version: '3.8'

services:
  postgres:
    container_name: portfolio_db
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD="trust"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_PORT}
  app:
    container_name: portfolio
    build:
      context: ./
    depends_on:
      - postgres
    restart: unless-stopped
    ports:
      - ${LOCAL_PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - LOCAL_PORT=${LOCAL_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_LOCAL_PORT=${POSTGRES_LOCAL_PORT}
      - POSTGRES_HOST=postgres
      - ACCESS_TOKEN_KEY=${ACCESS_TOKEN_KEY}
      - ACCESS_TOKEN_TIME=${ACCESS_TOKEN_TIME}
      - REFRESH_TOKEN_KEY=${REFRESH_TOKEN_KEY}
      - REFRESH_TOKEN_TIME=${REFRESH_TOKEN_TIME}